version: '3.9'
services:
  db:
    image: postgres
    container_name: dbTracknme
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tracknme_desafio
    volumes:
      - pgdata:/data/postgres
    network_mode: bridge
volumes:
  pgdata:
    driver: local
